services:
  zitadel:
    restart: "unless-stopped"
    networks:
      - "reverse-proxy_reverse-proxy-network"
      - "database_db-network"
      - "zitadel-network"
    image: "ghcr.io/zitadel/zitadel:latest"
    command:
      - "start-from-init"
      - "--config=/zitadel-config.yaml"
      #- "--config=/run/secrets/zitadel_secrets"
      - "--steps=/zitadel-init-steps.yaml"
      - "--masterkeyFile=/run/secrets/zitadel_masterkey"
    ports:
      - "3001:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.rule=Host(`auth.wvl.app`)"
      - "traefik.http.routers.zitadel.entrypoints=websecure"
      - "traefik.http.routers.zitadel.tls.certresolver=le"
    volumes:
      - /docker-volumes/zitadel/init-steps.yaml:/zitadel-init-steps.yaml:ro
      - /docker-volumes/zitadel/zitadel-config.yaml:/zitadel-config.yaml:ro
    secrets:
      - zitadel_secrets
      - zitadel_masterkey
#    healthcheck:
#      test: [ "CMD", "/app/zitadel", "ready" ]
#      interval: 10s
#      timeout: 60s
#      retries: 5
#      start_period: 10s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          pids: 99

secrets:
  zitadel_secrets:
    file: /docker-volumes/zitadel/zitadel_secrets.yaml
  zitadel_masterkey:
    file: /docker-volumes/zitadel/zitadel_masterkey

networks:
  zitadel-network:
  database_db-network:
    external: true
  reverse-proxy_reverse-proxy-network:
    external: true
